CREATE TABLE `lesson_plans` (
	`id` text PRIMARY KEY NOT NULL,
	`staff_id` text NOT NULL,
	`institution_id` text NOT NULL,
	`title` text NOT NULL,
	`subject` text NOT NULL,
	`grade_or_class` text NOT NULL,
	`date` text NOT NULL,
	`duration_minutes` integer NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`learning_objectives` text,
	`materials_needed` text,
	`introduction` text,
	`main_activity` text,
	`conclusion` text,
	`assessment_method` text,
	`homework_notes` text,
	`grade_book_id` text,
	`chapter_id` text,
	`is_deleted` integer DEFAULT 0,
	`created_at` text,
	`updated_at` text,
	FOREIGN KEY (`staff_id`) REFERENCES `staff`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`institution_id`) REFERENCES `institutions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`grade_book_id`) REFERENCES `grade_books`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`chapter_id`) REFERENCES `chapters`(`id`) ON UPDATE no action ON DELETE no action
);
