CREATE INDEX `admins_institution_id_idx` ON `admins` (`institution_id`);--> statement-breakpoint
CREATE INDEX `admins_is_deleted_idx` ON `admins` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `admins_is_active_idx` ON `admins` (`is_active`);--> statement-breakpoint
CREATE INDEX `classes_institution_id_idx` ON `classes` (`institution_id`);--> statement-breakpoint
CREATE INDEX `classes_is_deleted_idx` ON `classes` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `classes_is_active_idx` ON `classes` (`is_active`);--> statement-breakpoint
CREATE INDEX `classes_grade_idx` ON `classes` (`grade`);--> statement-breakpoint
CREATE INDEX `departments_institution_id_idx` ON `departments` (`institution_id`);--> statement-breakpoint
CREATE INDEX `departments_is_deleted_idx` ON `departments` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `institutions_is_deleted_idx` ON `institutions` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `institutions_is_active_idx` ON `institutions` (`is_active`);--> statement-breakpoint
CREATE INDEX `staff_institution_id_idx` ON `staff` (`institution_id`);--> statement-breakpoint
CREATE INDEX `staff_is_deleted_idx` ON `staff` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `staff_is_active_idx` ON `staff` (`is_active`);--> statement-breakpoint
CREATE INDEX `staff_type_idx` ON `staff` (`type`);--> statement-breakpoint
CREATE INDEX `students_institution_id_idx` ON `students` (`institution_id`);--> statement-breakpoint
CREATE INDEX `students_class_id_idx` ON `students` (`class_id`);--> statement-breakpoint
CREATE INDEX `students_is_deleted_idx` ON `students` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `students_is_active_idx` ON `students` (`is_active`);--> statement-breakpoint
CREATE INDEX `students_name_idx` ON `students` (`name`);--> statement-breakpoint
CREATE INDEX `chapter_contents_chapter_id_idx` ON `chapter_contents` (`chapter_id`);--> statement-breakpoint
CREATE INDEX `chapter_contents_type_idx` ON `chapter_contents` (`type`);--> statement-breakpoint
CREATE INDEX `chapters_grade_book_id_idx` ON `chapters` (`grade_book_id`);--> statement-breakpoint
CREATE INDEX `curricula_is_published_idx` ON `curricula` (`is_published`);--> statement-breakpoint
CREATE INDEX `grade_books_curriculum_id_idx` ON `grade_books` (`curriculum_id`);--> statement-breakpoint
CREATE INDEX `grade_books_grade_idx` ON `grade_books` (`grade`);--> statement-breakpoint
CREATE INDEX `grade_books_is_published_idx` ON `grade_books` (`is_published`);--> statement-breakpoint
CREATE INDEX `academic_year_terms_academic_year_id_idx` ON `academic_year_terms` (`academic_year_id`);--> statement-breakpoint
CREATE INDEX `class_session_topics_session_id_idx` ON `class_session_topics` (`session_id`);--> statement-breakpoint
CREATE INDEX `class_student_ids_class_id_idx` ON `class_student_ids` (`class_id`);--> statement-breakpoint
CREATE INDEX `class_student_ids_student_id_idx` ON `class_student_ids` (`student_id`);--> statement-breakpoint
CREATE INDEX `class_teacher_ids_class_id_idx` ON `class_teacher_ids` (`class_id`);--> statement-breakpoint
CREATE INDEX `class_teacher_ids_staff_id_idx` ON `class_teacher_ids` (`staff_id`);--> statement-breakpoint
CREATE INDEX `curriculum_grades_curriculum_id_idx` ON `curriculum_grades` (`curriculum_id`);--> statement-breakpoint
CREATE INDEX `curriculum_levels_curriculum_id_idx` ON `curriculum_levels` (`curriculum_id`);--> statement-breakpoint
CREATE INDEX `curriculum_tags_curriculum_id_idx` ON `curriculum_tags` (`curriculum_id`);--> statement-breakpoint
CREATE INDEX `grading_scale_entries_settings_id_idx` ON `grading_scale_entries` (`settings_id`);--> statement-breakpoint
CREATE INDEX `institution_accessible_gradebooks_access_id_idx` ON `institution_accessible_gradebooks` (`access_id`);--> statement-breakpoint
CREATE INDEX `institution_accessible_gradebooks_grade_book_id_idx` ON `institution_accessible_gradebooks` (`grade_book_id`);--> statement-breakpoint
CREATE INDEX `institution_admin_ids_institution_id_idx` ON `institution_admin_ids` (`institution_id`);--> statement-breakpoint
CREATE INDEX `institution_admin_ids_admin_id_idx` ON `institution_admin_ids` (`admin_id`);--> statement-breakpoint
CREATE INDEX `institution_curriculum_access_institution_id_idx` ON `institution_curriculum_access` (`institution_id`);--> statement-breakpoint
CREATE INDEX `institution_curriculum_access_curriculum_id_idx` ON `institution_curriculum_access` (`curriculum_id`);--> statement-breakpoint
CREATE INDEX `institution_staff_ids_institution_id_idx` ON `institution_staff_ids` (`institution_id`);--> statement-breakpoint
CREATE INDEX `institution_staff_ids_staff_id_idx` ON `institution_staff_ids` (`staff_id`);--> statement-breakpoint
CREATE INDEX `period_config_periods_period_config_id_idx` ON `period_config_periods` (`period_config_id`);--> statement-breakpoint
CREATE INDEX `period_config_working_days_period_config_id_idx` ON `period_config_working_days` (`period_config_id`);--> statement-breakpoint
CREATE INDEX `quiz_match_pairs_question_id_idx` ON `quiz_match_pairs` (`question_id`);--> statement-breakpoint
CREATE INDEX `quiz_question_options_question_id_idx` ON `quiz_question_options` (`question_id`);--> statement-breakpoint
CREATE INDEX `quiz_questions_content_id_idx` ON `quiz_questions` (`content_id`);--> statement-breakpoint
CREATE INDEX `staff_assigned_classes_staff_id_idx` ON `staff_assigned_classes` (`staff_id`);--> statement-breakpoint
CREATE INDEX `staff_assigned_classes_class_id_idx` ON `staff_assigned_classes` (`class_id`);--> statement-breakpoint
CREATE INDEX `staff_subjects_staff_id_idx` ON `staff_subjects` (`staff_id`);--> statement-breakpoint
CREATE INDEX `student_completed_contents_progress_id_idx` ON `student_completed_contents` (`progress_id`);--> statement-breakpoint
CREATE INDEX `student_completed_contents_content_id_idx` ON `student_completed_contents` (`content_id`);--> statement-breakpoint
CREATE INDEX `student_quiz_scores_progress_id_idx` ON `student_quiz_scores` (`progress_id`);--> statement-breakpoint
CREATE INDEX `student_quiz_scores_quiz_id_idx` ON `student_quiz_scores` (`quiz_id`);--> statement-breakpoint
CREATE INDEX `teaching_progress_contents_teaching_progress_id_idx` ON `teaching_progress_contents` (`teaching_progress_id`);--> statement-breakpoint
CREATE INDEX `teaching_progress_contents_content_id_idx` ON `teaching_progress_contents` (`content_id`);--> statement-breakpoint
CREATE INDEX `timetable_topics_covered_timetable_entry_id_idx` ON `timetable_topics_covered` (`timetable_entry_id`);--> statement-breakpoint
CREATE INDEX `academic_years_institution_id_idx` ON `academic_years` (`institution_id`);--> statement-breakpoint
CREATE INDEX `institution_settings_institution_id_idx` ON `institution_settings` (`institution_id`);--> statement-breakpoint
CREATE INDEX `period_configs_institution_id_idx` ON `period_configs` (`institution_id`);--> statement-breakpoint
CREATE INDEX `period_configs_is_deleted_idx` ON `period_configs` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `timetable_entries_staff_id_idx` ON `timetable_entries` (`staff_id`);--> statement-breakpoint
CREATE INDEX `timetable_entries_institution_id_idx` ON `timetable_entries` (`institution_id`);--> statement-breakpoint
CREATE INDEX `timetable_entries_is_deleted_idx` ON `timetable_entries` (`is_deleted`);--> statement-breakpoint
CREATE INDEX `timetable_entries_is_recurring_idx` ON `timetable_entries` (`is_recurring`);--> statement-breakpoint
CREATE INDEX `timetable_entries_day_of_week_idx` ON `timetable_entries` (`day_of_week`);--> statement-breakpoint
CREATE INDEX `timetable_entries_specific_date_idx` ON `timetable_entries` (`specific_date`);--> statement-breakpoint
CREATE INDEX `class_sessions_staff_id_idx` ON `class_sessions` (`staff_id`);--> statement-breakpoint
CREATE INDEX `class_sessions_institution_id_idx` ON `class_sessions` (`institution_id`);--> statement-breakpoint
CREATE INDEX `class_sessions_class_id_idx` ON `class_sessions` (`class_id`);--> statement-breakpoint
CREATE INDEX `class_sessions_status_idx` ON `class_sessions` (`status`);--> statement-breakpoint
CREATE INDEX `teaching_progress_institution_id_idx` ON `teaching_progress` (`institution_id`);--> statement-breakpoint
CREATE INDEX `teaching_progress_staff_id_idx` ON `teaching_progress` (`staff_id`);--> statement-breakpoint
CREATE INDEX `teaching_progress_class_id_idx` ON `teaching_progress` (`class_id`);--> statement-breakpoint
CREATE INDEX `teaching_progress_grade_book_id_idx` ON `teaching_progress` (`grade_book_id`);--> statement-breakpoint
CREATE INDEX `student_progress_user_id_idx` ON `student_progress` (`user_id`);--> statement-breakpoint
CREATE INDEX `student_progress_curriculum_id_idx` ON `student_progress` (`curriculum_id`);--> statement-breakpoint
CREATE INDEX `student_progress_grade_idx` ON `student_progress` (`grade`);--> statement-breakpoint
CREATE INDEX `student_progress_chapter_id_idx` ON `student_progress` (`chapter_id`);
