/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkDoneRouteImport } from './routes/work-done'
import { Route as TeachingDiaryRouteImport } from './routes/teaching-diary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as MyDraftsIndexRouteImport } from './routes/my-drafts/index'
import { Route as MyClassesIndexRouteImport } from './routes/my-classes/index'
import { Route as LessonPlansIndexRouteImport } from './routes/lesson-plans/index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions/index'
import { Route as ExaminationsIndexRouteImport } from './routes/examinations/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as StudentMyCoursesRouteImport } from './routes/student/my-courses'
import { Route as LessonPlansIdRouteImport } from './routes/lesson-plans/$id'
import { Route as InstructorDashboardRouteImport } from './routes/instructor/dashboard'
import { Route as InstructorCoursesRouteImport } from './routes/instructor/courses'
import { Route as InstitutionsIdRouteImport } from './routes/institutions/$id'
import { Route as ExaminationsIdRouteImport } from './routes/examinations/$id'
import { Route as CoursesIdRouteImport } from './routes/courses/$id'
import { Route as InstructorBatchesIndexRouteImport } from './routes/instructor/batches/index'
import { Route as InstructorBatchesBatchIdRouteImport } from './routes/instructor/batches/$batchId'

const WorkDoneRoute = WorkDoneRouteImport.update({
  id: '/work-done',
  path: '/work-done',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingDiaryRoute = TeachingDiaryRouteImport.update({
  id: '/teaching-diary',
  path: '/teaching-diary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDraftsIndexRoute = MyDraftsIndexRouteImport.update({
  id: '/my-drafts/',
  path: '/my-drafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClassesIndexRoute = MyClassesIndexRouteImport.update({
  id: '/my-classes/',
  path: '/my-classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPlansIndexRoute = LessonPlansIndexRouteImport.update({
  id: '/lesson-plans/',
  path: '/lesson-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsIndexRoute = ExaminationsIndexRouteImport.update({
  id: '/examinations/',
  path: '/examinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMyCoursesRoute = StudentMyCoursesRouteImport.update({
  id: '/student/my-courses',
  path: '/student/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPlansIdRoute = LessonPlansIdRouteImport.update({
  id: '/lesson-plans/$id',
  path: '/lesson-plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/instructor/dashboard',
  path: '/instructor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorCoursesRoute = InstructorCoursesRouteImport.update({
  id: '/instructor/courses',
  path: '/instructor/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIdRoute = InstitutionsIdRouteImport.update({
  id: '/institutions/$id',
  path: '/institutions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationsIdRoute = ExaminationsIdRouteImport.update({
  id: '/examinations/$id',
  path: '/examinations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorBatchesIndexRoute = InstructorBatchesIndexRouteImport.update({
  id: '/instructor/batches/',
  path: '/instructor/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorBatchesBatchIdRoute =
  InstructorBatchesBatchIdRouteImport.update({
    id: '/instructor/batches/$batchId',
    path: '/instructor/batches/$batchId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teaching-diary': typeof TeachingDiaryRoute
  '/work-done': typeof WorkDoneRoute
  '/courses/$id': typeof CoursesIdRoute
  '/examinations/$id': typeof ExaminationsIdRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/lesson-plans/$id': typeof LessonPlansIdRoute
  '/student/my-courses': typeof StudentMyCoursesRoute
  '/courses/': typeof CoursesIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/examinations/': typeof ExaminationsIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/lesson-plans/': typeof LessonPlansIndexRoute
  '/my-classes/': typeof MyClassesIndexRoute
  '/my-drafts/': typeof MyDraftsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/instructor/batches/$batchId': typeof InstructorBatchesBatchIdRoute
  '/instructor/batches/': typeof InstructorBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teaching-diary': typeof TeachingDiaryRoute
  '/work-done': typeof WorkDoneRoute
  '/courses/$id': typeof CoursesIdRoute
  '/examinations/$id': typeof ExaminationsIdRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/lesson-plans/$id': typeof LessonPlansIdRoute
  '/student/my-courses': typeof StudentMyCoursesRoute
  '/courses': typeof CoursesIndexRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/examinations': typeof ExaminationsIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/lesson-plans': typeof LessonPlansIndexRoute
  '/my-classes': typeof MyClassesIndexRoute
  '/my-drafts': typeof MyDraftsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/students': typeof StudentsIndexRoute
  '/instructor/batches/$batchId': typeof InstructorBatchesBatchIdRoute
  '/instructor/batches': typeof InstructorBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teaching-diary': typeof TeachingDiaryRoute
  '/work-done': typeof WorkDoneRoute
  '/courses/$id': typeof CoursesIdRoute
  '/examinations/$id': typeof ExaminationsIdRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/lesson-plans/$id': typeof LessonPlansIdRoute
  '/student/my-courses': typeof StudentMyCoursesRoute
  '/courses/': typeof CoursesIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/examinations/': typeof ExaminationsIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/lesson-plans/': typeof LessonPlansIndexRoute
  '/my-classes/': typeof MyClassesIndexRoute
  '/my-drafts/': typeof MyDraftsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/instructor/batches/$batchId': typeof InstructorBatchesBatchIdRoute
  '/instructor/batches/': typeof InstructorBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teaching-diary'
    | '/work-done'
    | '/courses/$id'
    | '/examinations/$id'
    | '/institutions/$id'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/lesson-plans/$id'
    | '/student/my-courses'
    | '/courses/'
    | '/curriculum/'
    | '/dashboard/'
    | '/examinations/'
    | '/institutions/'
    | '/lesson-plans/'
    | '/my-classes/'
    | '/my-drafts/'
    | '/reports/'
    | '/settings/'
    | '/staff/'
    | '/students/'
    | '/instructor/batches/$batchId'
    | '/instructor/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teaching-diary'
    | '/work-done'
    | '/courses/$id'
    | '/examinations/$id'
    | '/institutions/$id'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/lesson-plans/$id'
    | '/student/my-courses'
    | '/courses'
    | '/curriculum'
    | '/dashboard'
    | '/examinations'
    | '/institutions'
    | '/lesson-plans'
    | '/my-classes'
    | '/my-drafts'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/students'
    | '/instructor/batches/$batchId'
    | '/instructor/batches'
  id:
    | '__root__'
    | '/'
    | '/teaching-diary'
    | '/work-done'
    | '/courses/$id'
    | '/examinations/$id'
    | '/institutions/$id'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/lesson-plans/$id'
    | '/student/my-courses'
    | '/courses/'
    | '/curriculum/'
    | '/dashboard/'
    | '/examinations/'
    | '/institutions/'
    | '/lesson-plans/'
    | '/my-classes/'
    | '/my-drafts/'
    | '/reports/'
    | '/settings/'
    | '/staff/'
    | '/students/'
    | '/instructor/batches/$batchId'
    | '/instructor/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeachingDiaryRoute: typeof TeachingDiaryRoute
  WorkDoneRoute: typeof WorkDoneRoute
  CoursesIdRoute: typeof CoursesIdRoute
  ExaminationsIdRoute: typeof ExaminationsIdRoute
  InstitutionsIdRoute: typeof InstitutionsIdRoute
  InstructorCoursesRoute: typeof InstructorCoursesRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  LessonPlansIdRoute: typeof LessonPlansIdRoute
  StudentMyCoursesRoute: typeof StudentMyCoursesRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ExaminationsIndexRoute: typeof ExaminationsIndexRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  LessonPlansIndexRoute: typeof LessonPlansIndexRoute
  MyClassesIndexRoute: typeof MyClassesIndexRoute
  MyDraftsIndexRoute: typeof MyDraftsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  InstructorBatchesBatchIdRoute: typeof InstructorBatchesBatchIdRoute
  InstructorBatchesIndexRoute: typeof InstructorBatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-done': {
      id: '/work-done'
      path: '/work-done'
      fullPath: '/work-done'
      preLoaderRoute: typeof WorkDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaching-diary': {
      id: '/teaching-diary'
      path: '/teaching-diary'
      fullPath: '/teaching-diary'
      preLoaderRoute: typeof TeachingDiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-drafts/': {
      id: '/my-drafts/'
      path: '/my-drafts'
      fullPath: '/my-drafts/'
      preLoaderRoute: typeof MyDraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-classes/': {
      id: '/my-classes/'
      path: '/my-classes'
      fullPath: '/my-classes/'
      preLoaderRoute: typeof MyClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-plans/': {
      id: '/lesson-plans/'
      path: '/lesson-plans'
      fullPath: '/lesson-plans/'
      preLoaderRoute: typeof LessonPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations/': {
      id: '/examinations/'
      path: '/examinations'
      fullPath: '/examinations/'
      preLoaderRoute: typeof ExaminationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/my-courses': {
      id: '/student/my-courses'
      path: '/student/my-courses'
      fullPath: '/student/my-courses'
      preLoaderRoute: typeof StudentMyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-plans/$id': {
      id: '/lesson-plans/$id'
      path: '/lesson-plans/$id'
      fullPath: '/lesson-plans/$id'
      preLoaderRoute: typeof LessonPlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/instructor/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/courses': {
      id: '/instructor/courses'
      path: '/instructor/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/$id': {
      id: '/institutions/$id'
      path: '/institutions/$id'
      fullPath: '/institutions/$id'
      preLoaderRoute: typeof InstitutionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examinations/$id': {
      id: '/examinations/$id'
      path: '/examinations/$id'
      fullPath: '/examinations/$id'
      preLoaderRoute: typeof ExaminationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/batches/': {
      id: '/instructor/batches/'
      path: '/instructor/batches'
      fullPath: '/instructor/batches/'
      preLoaderRoute: typeof InstructorBatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/batches/$batchId': {
      id: '/instructor/batches/$batchId'
      path: '/instructor/batches/$batchId'
      fullPath: '/instructor/batches/$batchId'
      preLoaderRoute: typeof InstructorBatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeachingDiaryRoute: TeachingDiaryRoute,
  WorkDoneRoute: WorkDoneRoute,
  CoursesIdRoute: CoursesIdRoute,
  ExaminationsIdRoute: ExaminationsIdRoute,
  InstitutionsIdRoute: InstitutionsIdRoute,
  InstructorCoursesRoute: InstructorCoursesRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  LessonPlansIdRoute: LessonPlansIdRoute,
  StudentMyCoursesRoute: StudentMyCoursesRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ExaminationsIndexRoute: ExaminationsIndexRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  LessonPlansIndexRoute: LessonPlansIndexRoute,
  MyClassesIndexRoute: MyClassesIndexRoute,
  MyDraftsIndexRoute: MyDraftsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  InstructorBatchesBatchIdRoute: InstructorBatchesBatchIdRoute,
  InstructorBatchesIndexRoute: InstructorBatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
