/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as MyClassesIndexRouteImport } from './routes/my-classes/index'
import { Route as LessonPlansIndexRouteImport } from './routes/lesson-plans/index'
import { Route as InstitutionsIndexRouteImport } from './routes/institutions/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as LessonPlansIdRouteImport } from './routes/lesson-plans/$id'
import { Route as InstitutionsIdRouteImport } from './routes/institutions/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClassesIndexRoute = MyClassesIndexRouteImport.update({
  id: '/my-classes/',
  path: '/my-classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPlansIndexRoute = LessonPlansIndexRouteImport.update({
  id: '/lesson-plans/',
  path: '/lesson-plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIndexRoute = InstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPlansIdRoute = LessonPlansIdRouteImport.update({
  id: '/lesson-plans/$id',
  path: '/lesson-plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsIdRoute = InstitutionsIdRouteImport.update({
  id: '/institutions/$id',
  path: '/institutions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/lesson-plans/$id': typeof LessonPlansIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/lesson-plans/': typeof LessonPlansIndexRoute
  '/my-classes/': typeof MyClassesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/lesson-plans/$id': typeof LessonPlansIdRoute
  '/courses': typeof CoursesIndexRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/institutions': typeof InstitutionsIndexRoute
  '/lesson-plans': typeof LessonPlansIndexRoute
  '/my-classes': typeof MyClassesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/students': typeof StudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/institutions/$id': typeof InstitutionsIdRoute
  '/lesson-plans/$id': typeof LessonPlansIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/institutions/': typeof InstitutionsIndexRoute
  '/lesson-plans/': typeof LessonPlansIndexRoute
  '/my-classes/': typeof MyClassesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/students/': typeof StudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/institutions/$id'
    | '/lesson-plans/$id'
    | '/courses/'
    | '/curriculum/'
    | '/dashboard/'
    | '/institutions/'
    | '/lesson-plans/'
    | '/my-classes/'
    | '/reports/'
    | '/settings/'
    | '/staff/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/institutions/$id'
    | '/lesson-plans/$id'
    | '/courses'
    | '/curriculum'
    | '/dashboard'
    | '/institutions'
    | '/lesson-plans'
    | '/my-classes'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/institutions/$id'
    | '/lesson-plans/$id'
    | '/courses/'
    | '/curriculum/'
    | '/dashboard/'
    | '/institutions/'
    | '/lesson-plans/'
    | '/my-classes/'
    | '/reports/'
    | '/settings/'
    | '/staff/'
    | '/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstitutionsIdRoute: typeof InstitutionsIdRoute
  LessonPlansIdRoute: typeof LessonPlansIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  InstitutionsIndexRoute: typeof InstitutionsIndexRoute
  LessonPlansIndexRoute: typeof LessonPlansIndexRoute
  MyClassesIndexRoute: typeof MyClassesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-classes/': {
      id: '/my-classes/'
      path: '/my-classes'
      fullPath: '/my-classes/'
      preLoaderRoute: typeof MyClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-plans/': {
      id: '/lesson-plans/'
      path: '/lesson-plans'
      fullPath: '/lesson-plans/'
      preLoaderRoute: typeof LessonPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/': {
      id: '/institutions/'
      path: '/institutions'
      fullPath: '/institutions/'
      preLoaderRoute: typeof InstitutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson-plans/$id': {
      id: '/lesson-plans/$id'
      path: '/lesson-plans/$id'
      fullPath: '/lesson-plans/$id'
      preLoaderRoute: typeof LessonPlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions/$id': {
      id: '/institutions/$id'
      path: '/institutions/$id'
      fullPath: '/institutions/$id'
      preLoaderRoute: typeof InstitutionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstitutionsIdRoute: InstitutionsIdRoute,
  LessonPlansIdRoute: LessonPlansIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  InstitutionsIndexRoute: InstitutionsIndexRoute,
  LessonPlansIndexRoute: LessonPlansIndexRoute,
  MyClassesIndexRoute: MyClassesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
